# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
# - task: UiPathInstallPlatform@4
#   inputs:
#     cliVersion: 'WIN_23.6.8581.19168'
# - task: UiPathPack@4
#   inputs:
#     versionType: 'AutoVersion'
#     projectJsonPath: 'project.json'
#     outputType: 'Process'
#     orchestratorConnection: 'DemoCICD23022023'
#     outputPath: '$(Build.ArtifactStagingDirectory)\Output'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'DemoCICD'
#     publishLocation: 'Container'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Tests'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'


- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'DemoCICD23022023'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    createProcess: false
    folderName: 'Meera'

